# Generated by Django 3.2.9 on 2021-11-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211115_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='schemas',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='schemas',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
    ]
