# Generated by Django 3.2.9 on 2021-11-19 16:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211119_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='Cette description sera le corps de la page de détail du dispositif, il est inutil de le remplir si il y a un lien externe', verbose_name='description'),
        ),
    ]
