# Generated by Django 3.2.9 on 2021-11-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211119_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='schemas',
            new_name='schemes',
        ),
    ]
