# Generated by Django 3.2.9 on 2021-11-25 11:00

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_schemas_contentpage_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text="Corps de la page de détail du dispositif, ignorer s'il y a un lien externe", verbose_name='description'),
        ),
    ]
