# Generated by Django 3.2.9 on 2021-11-30 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0008_auto_20211125_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForWhoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='Ignorer ce champ, il sera rempli automatiquement', max_length=100, unique=True, verbose_name='slug')),
                ('long_name', models.CharField(help_text="Nom du filtre tel que l'utilisateur le vois affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom du filtre')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': "tag 'Pour qui?'",
                'verbose_name_plural': "tags 'Pour qui?'",
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ForWhatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='Ignorer ce champ, il sera rempli automatiquement', max_length=100, unique=True, verbose_name='slug')),
                ('long_name', models.CharField(help_text="Nom du filtre tel que l'utilisateur le vois affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom du filtre')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': "tag 'Pour quoi?'",
                'verbose_name_plural': "tags 'Pour quoi?'",
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='scheme',
            name='for_what_tags',
            field=models.ManyToManyField(blank=True, to='home.ForWhatTag', verbose_name="Tags 'Pour quoi?'"),
        ),
        migrations.AddField(
            model_name='scheme',
            name='for_who_tags',
            field=models.ManyToManyField(blank=True, to='home.ForWhoTag', verbose_name="Tags 'Pour qui?'"),
        ),
    ]
