# Generated by Django 3.2.9 on 2021-12-02 08:31

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='schemes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Scheme', verbose_name='Dispositifs reliés'),
        ),
    ]
