# Generated by Django 3.2.9 on 2021-12-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_newslistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide le block concernant les actualités ne s'affichera pas sur l'accueil", max_length=255, verbose_name="titre du block d'actualité"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_first',
            field=models.ForeignKey(blank=True, help_text="Première actualité à mettre en avant sur la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.news'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_second',
            field=models.ForeignKey(blank=True, help_text="Deuxième actualité à mettre en avant sur la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.news'),
        ),
    ]
