# Generated by Django 3.2.9 on 2021-12-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide la mise en avant des actualités ne s'affichera pas sur l'accueil", max_length=255, verbose_name="titre du block d'actualité"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_first',
            field=models.ForeignKey(blank=True, help_text="Première actualité à mettre en avant sur la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.news', verbose_name='Première actualité'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_second',
            field=models.ForeignKey(blank=True, help_text="Deuxième actualité à mettre en avant sur la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.news', verbose_name='Second actualité'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.IntegerBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))], label='chiffre clé'))), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text="Corps de la page de détail du dispositif, ignorer s'il y a un lien externe", verbose_name='description'),
        ),
    ]
