# Generated by Django 3.2.9 on 2021-12-08 09:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_scheme_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='paragraphe')), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue'))], blank=True, help_text="Corps de la page de détail du dispositif, ignorer s'il y a un lien externe", verbose_name='description'),
        ),
    ]
