# Generated by Django 3.2.9 on 2021-12-08 17:46

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211208_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_call_action',
            field=models.CharField(default='A CHANGER', max_length=255, verbose_name='résumé de notre mission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue'))], blank=True, help_text='Corps de la page', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue'))], blank=True, help_text='Corps de la page', verbose_name='description'),
        ),
    ]
