# Generated by Django 3.2.9 on 2021-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211209_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwhattag',
            name='long_name',
            field=models.CharField(help_text="Nom du filtre tel que l'utilisateur le voit affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom du filtre'),
        ),
        migrations.AlterField(
            model_name='forwhattag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='forwhotag',
            name='long_name',
            field=models.CharField(help_text="Nom du filtre tel que l'utilisateur le voit affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom du filtre'),
        ),
        migrations.AlterField(
            model_name='forwhotag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
