# Generated by Django 3.2.9 on 2021-12-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20211210_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Page de contenu', 'verbose_name_plural': 'Pages de contenu'},
        ),
        migrations.AlterModelOptions(
            name='newslistpage',
            options={'verbose_name': 'Accueil des actualités', 'verbose_name_plural': 'Accueils des actualités'},
        ),
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Renseigner si différent de la date de début', null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='news',
            name='place',
            field=models.CharField(blank=True, help_text="Sera affiché si c'est un évènement", max_length=255, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text="Sera affiché si c'est un évènement", null=True, verbose_name='Date de début'),
        ),
        migrations.DeleteModel(
            name='HomePageTwitterAccount',
        ),
    ]
