# Generated by Django 3.2.9 on 2021-12-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211215_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['publication_date'], 'verbose_name': 'Actualité / Evènement', 'verbose_name_plural': 'Actualités / Evènements'},
        ),
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text="Permet de trier l'ordre d'affichage dans /actualites", verbose_name='Date de publication'),
        ),
    ]
