# Generated by Django 3.2.9 on 2021-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211215_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='home.Scheme', verbose_name='Dispositifs reliés'),
        ),
    ]
