# Generated by Django 3.2.9 on 2021-12-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0025_alter_news_schemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='URL de votre page Facebook')),
                ('instagram', models.CharField(help_text='URL de votre page Instagram', max_length=255)),
                ('linkedin', models.URLField(help_text='URL de votre page LinkedIn')),
                ('youtube', models.URLField(help_text='URL de votre page YouTube')),
                ('twitter', models.URLField(help_text='URL de votre page Twitter')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Comptes des réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsLetter', models.URLField(help_text="Lien d'inscription à la lettre d'information")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': "Inscription à la lettre d'information",
            },
        ),
    ]
