# Generated by Django 3.2.9 on 2021-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_newslettersettings_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(help_text='URL de votre page Instagram'),
        ),
    ]
