# Generated by Django 3.2.10 on 2021-12-17 10:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_socialmediasettings_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue')), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(label='Url')), ('legend', wagtail.core.blocks.CharBlock(label='Légende')), ('height', wagtail.core.blocks.IntegerBlock(default=50, label="Hauteur en pourcentage d'écran", max_value=100, min_value=0))], label='Cadre intégré (iframe)'))], blank=True, help_text='Corps de la page', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue')), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(label='Url')), ('legend', wagtail.core.blocks.CharBlock(label='Légende')), ('height', wagtail.core.blocks.IntegerBlock(default=50, label="Hauteur en pourcentage d'écran", max_value=100, min_value=0))], label='Cadre intégré (iframe)'))], blank=True, help_text='Corps de la page', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='titre')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'], label='paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('key_figure', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.CharBlock(label='chiffre')), ('label', wagtail.core.blocks.CharBlock(label='label'))]), label='chiffre clé')), ('quote', wagtail.core.blocks.StructBlock([('source_link', wagtail.core.blocks.CharBlock(label='lien vers la source', required=False)), ('quote', wagtail.core.blocks.CharBlock(label='citation')), ('author', wagtail.core.blocks.CharBlock(label='auteurice', required=False)), ('book', wagtail.core.blocks.CharBlock(label='livre', required=False)), ('details', wagtail.core.blocks.CharBlock(label='détails', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='citation')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock()), ('highlight', wagtail.core.blocks.CharBlock(label='mise en exergue')), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(label='Url')), ('legend', wagtail.core.blocks.CharBlock(label='Légende')), ('height', wagtail.core.blocks.IntegerBlock(default=50, label="Hauteur en pourcentage d'écran", max_value=100, min_value=0))], label='Cadre intégré (iframe)'))], blank=True, help_text='Corps de la page', verbose_name='description'),
        ),
    ]
