# Generated by Django 3.2.9 on 2021-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211217_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersettings',
            name='newsLetter',
            field=models.URLField(blank=True, help_text="Lien d'inscription à la lettre d'information", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL de votre page Facebook', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL de votre page Instagram', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL de votre page LinkedIn', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL de votre page Twitter', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL de votre page YouTube', null=True),
        ),
    ]
