# Generated by Django 3.2.9 on 2021-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211217_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='home.Scheme', verbose_name='Dispositifs reliés'),
        ),
    ]
