# Generated by Django 3.2.9 on 2021-12-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_scheme_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwhattag',
            name='long_name_en',
            field=models.CharField(default='long name', help_text="Nom du filtre tel que l'utilisateur le voit affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom anglais du filtre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwhattag',
            name='name_en',
            field=models.CharField(default='name', max_length=100, verbose_name='nom anglais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwhotag',
            name='long_name_en',
            field=models.CharField(default='long name', help_text="Nom du filtre tel que l'utilisateur le voit affiché (peut être plus précis que le nom du tag)", max_length=255, verbose_name='nom anglais du filtre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwhotag',
            name='name_en',
            field=models.CharField(default='name', max_length=100, verbose_name='nom anglais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Est un évènement ?'),
        ),
    ]
