# Generated by Django 3.2.9 on 2021-12-20 12:53

from django.db import migrations, models
from django.utils.text import slugify


def add_slugs(apps, _):
    News = apps.get_model("home", "News")
    for news in News.objects.all():
        news.slug = slugify(news.name)
        news.save()


def undo_add_slugs(*_):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_auto_20211220_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                max_length=100, null=True, verbose_name="slug (URL de l'actualité"
            ),
        ),
        migrations.RunPython(add_slugs, undo_add_slugs),
    ]
