# Generated by Django 3.2.9 on 2021-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True, verbose_name="slug (URL de l'actualité"),
            preserve_default=False,
        ),
    ]
