# Generated by Django 3.2.9 on 2021-12-20 13:38

from django.db import migrations, models
from django.utils.text import slugify


def add_slugs(apps, _):
    Scheme = apps.get_model("home", "Scheme")
    for scheme in Scheme.objects.all():
        scheme.slug = slugify(scheme.name)
        if scheme.locale.language_code != "fr":
            scheme.slug += f"__{scheme.locale.language_code}"
        scheme.save()


def undo_add_slugs(*_):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name="slug (URL de l'actualité)"),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug (URL de l'actualité)"),
        ),
        migrations.RunPython(add_slugs, undo_add_slugs),
    ]
