# Generated by Django 3.2.9 on 2021-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20211220_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True, verbose_name="slug (URL de l'actualité)"),
            preserve_default=False,
        ),
    ]
