# Generated by Django 3.2.9 on 2021-12-20 20:05

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_scheme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='schemes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Scheme', verbose_name='Dispositifs liés'),
        ),
    ]
