# Generated by Django 3.2.9 on 2021-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_contentpage_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='search_description',
            field=models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='search_description',
            field=models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='seo_title',
            field=models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, verbose_name='title tag'),
        ),
    ]
