# Generated by Django 3.2.9 on 2022-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20211220_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name="slug (URL de l'actualité)"),
        ),
    ]
