# Generated by Django 3.2.9 on 2022-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_scheme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name="slug (URL de l'actualité)"),
        ),
    ]
