# Generated by Django 3.2.9 on 2022-01-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0044_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='labo_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide, la la mise en avant du Labo ne s'affichera pas sur l'accueil", max_length=255, verbose_name='titre pour la mise en avant du Labo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labo_description',
            field=models.CharField(blank=True, max_length=510, verbose_name='Description du Labo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image pour la mise en avant du Labo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labo_tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slogan / Titre du Labo'),
        ),
    ]
