# Generated by Django 3.2.9 on 2022-01-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0045_auto_20220120_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='labo_block_title',
            field=models.CharField(blank=True, help_text="Si ce champ est vide, la mise en avant du Labo ne s'affichera pas sur l'accueil", max_length=255, verbose_name='titre pour la mise en avant du Labo'),
        ),
        migrations.CreateModel(
            name='LaboSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labo_link', models.URLField(blank=True, help_text='Lien vers le Labo Société Numérique', max_length=300, null=True)),
                ('in_social_network_banner', models.BooleanField(default=False, verbose_name='Afficher dans le bandeaux des réseaux sociaux ?')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Labo Société Numérique',
            },
        ),
    ]
